version: '3.8'

services:

  backend:
    image: devsourabh123/lead-tracker-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    image: devsourabh123/lead-tracker-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend